# Generated by Django 3.2.4 on 2021-06-13 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='limit',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 14, 9, 39, 6, 599314, tzinfo=utc)),
        ),
    ]
